In [1]:
import os
import numpy, scipy, matplotlib.pyplot as plt, IPython.display as ipd
import librosa, librosa.display
import numpy as np
import math
os.chdir('/home/student/Downloads/new_violin_viola/baroque/viola/combined_train')
x1=[]
y_train=[]
mfcc_list_mean = []
mfcc_list_std = []

freqViolin = []
freqViola = []
for f_name in os.listdir('/home/student/Downloads/new_violin_viola/baroque/viola/combined_train'):
    if f_name.endswith('.mp3') or f_name.endswith('.wav'):
        print(f_name)
        #temp = x/x.max()  #normalization
        #S = librosa.feature.melspectrogram(temp, sr=sr, n_mels=128)  # 128 mel bands
        #mfcc = librosa.feature.mfcc(S=librosa.power_to_db(S), n_mfcc=13)
        #tempList = list(np.mean(mfcc,1))
        #tempList1 = list(np.std(mfcc,1))
        x, sr = librosa.load(f_name)
        hop_length = 512
        X = librosa.stft(x)
        S = librosa.amplitude_to_db(X, ref=np.max)
        
        l1 =[]
        #by default, there are 1025 frequency bins in 0 to sr/2 (sr = 22050)
        
        
        hist=[]
        hist1=[]
        for i in range(len(S)):
            for j in range(len(S[0])):
        
                if S[i][j]>=(-11):
                    temp = i *((22050/2)/1025)
            
                    if temp >0:
                        hist.append(math.log2(temp))
                        hist1.append(temp)
        x1.append(hist)
        freqViola.append(hist1)
        y_train.append("viola")
os.chdir('/home/student/Downloads/new_violin_viola/baroque/violin/combined_train')  
for f_name in os.listdir('/home/student/Downloads/new_violin_viola/baroque/violin/combined_train'):
    if f_name.endswith('.mp3') or f_name.endswith('.wav'):
        print(f_name)
        
        x, sr = librosa.load(f_name)
        hop_length = 512
        X = librosa.stft(x)
        S = librosa.amplitude_to_db(X, ref=np.max)
        
        l1 =[]
        #by default, there are 1025 frequency bins in 0 to sr/2 (sr = 22050)

        
        hist=[]
        hist1=[]
        for i in range(len(S)):
            for j in range(len(S[0])):
        
                if S[i][j]>=(-11):
                    temp = i *((22050/2)/1025)
            
                    if temp >0:
                        hist.append(math.log2(temp))
                        hist1.append(temp)
                        
        x1.append(hist)
        freqViolin.append(hist1)
        y_train.append("violin")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import statistics 


X_train= [[statistics.mean(a), statistics.median(a),  min(a), max(a),np.percentile(np.array(a), 25), np.percentile(np.array(a), 75)] for a in x1]
#y=["violin","violin","violin","violin","violin","viola","viola","viola","viola","viola"]
    

/home/student/.local/lib/python3.6/site-packages/numba/core/errors.py:154: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)


Bach_Viola_Concerto_PROCESSED.wav


/home/student/.local/lib/python3.6/site-packages/librosa/core/spectrum.py:1642: UserWarning: amplitude_to_db was called on complex input so phase information will be discarded. To suppress this warning, call amplitude_to_db(np.abs(S)) instead.
  "amplitude_to_db was called on complex input so phase "


Viola Concerto in G Major-1st Mov_PROCESSED.wav
[Iris Hur] Handel-Casadesus Viola Concerto 1st Movement_PROCESSED.wav
[Yoonah Park] Bach Viola Concerto in C minor 3rd movement_PROCESSED.wav
Sonata No. 3 in F Major I Adagio _processed.wav
[Yoonah Park] Bach Viola Concerto in C Minor 1st Movement_PROCESSED.wav
Viola Da Gamba_PROCESSED_PROCESSED.wav
Minuet No 3_PROCESSED.wav
Minuet No 1_PROCESSED.wav
Viola Concerto in G Major-4th Mov_PROCESSED.wav
Sonata No. 3 in F Major III LargoPROCESSED.wav
Viola Concerto in G Major-2nd Mov_PROCESSED.wav
Vivaldi - Sonata for Viola and Piano in B flat_PROCESSED.wav
Vivaldi sonata in a minor (viola arr_PROCESSED.wav
Sonata in B minor, BWV 1014 II - Allegro_PROCESSED.wav
Vivaldi Violin Concerto in E_PROCESSED.wav
Sonata in B minor, BWV 1014 IV -Allegro_PROCESSED.wav
Sonata in G BWV 1019I - Allegro_PROCESSED.wav
Sonata in C minor H 514 I -Allegro moderato_PROCESSED.wav
Sonata in G BWV 1019 II -Largo_PROCESSED.wav
Sonata in C minor H 514 II -Adagio ma non 

In [2]:
os.chdir('/home/student/Downloads/new_violin_viola/baroque/viola/combined_test')
x1=[]
y_test=[]
for f_name in os.listdir('/home/student/Downloads/new_violin_viola/baroque/viola/combined_test'):
    if f_name.endswith('.mp3') or f_name.endswith('.wav'):
        print(f_name)
        
        x, sr = librosa.load(f_name)
        hop_length = 512
        X = librosa.stft(x)
        S = librosa.amplitude_to_db(X, ref=np.max)
        
        l1 =[]
        #by default, there are 1025 frequency bins in 0 to sr/2 (sr = 22050)

        
        hist=[]
        hist1=[]
        for i in range(len(S)):
            for j in range(len(S[0])):
        
                if S[i][j]>=(-11):
                    temp = i *((22050/2)/1025)
            
                    if temp >0:
                        hist.append(math.log2(temp))
                        hist1.append(temp)
                        
                        
        x1.append(hist)
        freqViola.append(hist1)
        y_test.append("viola")
os.chdir('/home/student/Downloads/new_violin_viola/baroque/violin/combined_test')  
for f_name in os.listdir('/home/student/Downloads/new_violin_viola/baroque/violin/combined_test'):
    if f_name.endswith('.mp3') or f_name.endswith('.wav'):
        print(f_name)
        
        x, sr = librosa.load(f_name)
        hop_length = 512
        X = librosa.stft(x)
        S = librosa.amplitude_to_db(X, ref=np.max)
        
        l1 =[]
        #by default, there are 1025 frequency bins in 0 to sr/2 (sr = 22050)

        
        hist=[]
        hist1=[]
        for i in range(len(S)):
            for j in range(len(S[0])):
        
                if S[i][j]>=(-11):
                    temp = i *((22050/2)/1025)
            
                    if temp >0:
                        hist.append(math.log2(temp))
                        hist1.append(temp)
                        
        x1.append(hist)
        freqViolin.append(hist1)
        y_test.append("violin")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import statistics 

X_test= [[statistics.mean(a), statistics.median(a),  min(a), max(a),np.percentile(np.array(a), 25), np.percentile(np.array(a), 75)] for a in x1]

 

Vivaldi Sonata No.5 in E Minor, Allegro, for Viola and Piano_PROCESSED.wav


/home/student/.local/lib/python3.6/site-packages/librosa/core/spectrum.py:1642: UserWarning: amplitude_to_db was called on complex input so phase information will be discarded. To suppress this warning, call amplitude_to_db(np.abs(S)) instead.
  "amplitude_to_db was called on complex input so phase "


Sonata No. 3 in F Major II Allegro_PROCESSED.wav
Viola Concerto in G Major-3rd Mov_PROCESSED.wav
Air Suite, Viola _ Piano_PROCESSED.wav
Sonata No. 3 in F Major IV Allegro _PROCESSED.wav
Viola Da Gamba_PROCESSED.wav
Sonata in C minor, H 514 III -Presto_PROCESSED.wav
Sonata in G, BWV 1019 V -Allegro_PROCESSED.wav
Sonata in A, BWV 1015 III -Andante un poco_PROCESSED.wav
Sonata in A, BWV 1015-Dolce_PROCESSED.wav
Vivaldi - Violin Concerto in G minor, RV315 Summer , III_PROCESSED.wav
Sonata in B minor, BWV 1014-Adagio_PROCESSED.wav


In [3]:
from numpy.random import seed
seed(14) 
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
classifier = RandomForestClassifier(max_depth=10, random_state=0)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('Accuracy' + str(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[5 1]
 [1 5]]
Accuracy0.8333333333333334
              precision    recall  f1-score   support

       viola       0.83      0.83      0.83         6
      violin       0.83      0.83      0.83         6

    accuracy                           0.83        12
   macro avg       0.83      0.83      0.83        12
weighted avg       0.83      0.83      0.83        12

Accuracy: 0.8333333333333334


In [4]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)

# Train the model using the training sets
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('Accuracy' + str(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[2 4]
 [1 5]]
Accuracy0.5833333333333334
              precision    recall  f1-score   support

       viola       0.67      0.33      0.44         6
      violin       0.56      0.83      0.67         6

    accuracy                           0.58        12
   macro avg       0.61      0.58      0.56        12
weighted avg       0.61      0.58      0.56        12

Accuracy: 0.5833333333333334


In [5]:
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(random_state=42,kernel='linear') # Linear Kernel

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('Accuracy' + str(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[2 4]
 [1 5]]
Accuracy0.5833333333333334
              precision    recall  f1-score   support

       viola       0.67      0.33      0.44         6
      violin       0.56      0.83      0.67         6

    accuracy                           0.58        12
   macro avg       0.61      0.58      0.56        12
weighted avg       0.61      0.58      0.56        12

Accuracy: 0.5833333333333334


In [6]:
svm = svm.SVC(random_state=42, kernel='rbf')
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('Accuracy' + str(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[3 3]
 [1 5]]
Accuracy0.6666666666666666
              precision    recall  f1-score   support

       viola       0.75      0.50      0.60         6
      violin       0.62      0.83      0.71         6

    accuracy                           0.67        12
   macro avg       0.69      0.67      0.66        12
weighted avg       0.69      0.67      0.66        12

Accuracy: 0.6666666666666666


In [7]:
#statistics.mean(freqViola), statistics.median(freqViola),  np.percentile(np.array(freqViola), 25), np.percentile(np.array(freqViola), 75)
#viola1= [[statistics.mean(freqViola[i])] for i in range(len(freqViola))]

In [8]:
#freqViola
#freqViolin
#mean, median, mode, 25th, 75th
from statistics import stdev 
viola1= [[statistics.mean(a), statistics.median(a),  np.percentile(np.array(a), 25), np.percentile(np.array(a), 75)] for a in freqViola]
violin1= [[statistics.mean(a), statistics.median(a), np.percentile(np.array(a), 25), np.percentile(np.array(a), 75)] for a in freqViolin]
meanstdViolaList = []
for i in viola1:
    meanstdViolaList.append(i[0])
meanstdViola = stdev(meanstdViolaList)
print("Standard deviation of mean Viola frequency: " + str(meanstdViola))

meanstdViolinList = []
for i in violin1:
    meanstdViolinList.append(i[0])
meanstdViolin = stdev(meanstdViolinList)
print("Standard deviation of mean Violin frequency: " + str(meanstdViolin))

Standard deviation of mean Viola frequency: 278.6899184168908
Standard deviation of mean Violin frequency: 282.72566501856346


In [9]:
medianstdViolaList = []
for i in viola1:
    medianstdViolaList.append(i[1])
medianstdViola = stdev(medianstdViolaList)
print("Standard deviation of median Viola frequency: " + str(medianstdViola))

medianstdViolinList = []
for i in violin1:
    medianstdViolinList.append(i[1])
medianstdViolin = stdev(medianstdViolinList)
print("Standard deviation of median Violin frequency: " + str(medianstdViolin))

Standard deviation of median Viola frequency: 249.4730083499519
Standard deviation of median Violin frequency: 243.0541114595769


In [10]:
#modestdViolaList = []
#for i in viola1:
#    modestdViolaList.append(i[2])
#modestdViola = stdev(modestdViolaList)
#print("Standard deviation of mode Viola frequency: " + str(modestdViola))

#modestdViolinList = []
#for i in violin1:
#    modestdViolinList.append(i[2])
#modestdViolin = stdev(modestdViolinList)
#print("Standard deviation of mode Violin frequency: " + str(modestdViolin))

In [11]:
temp = []

for i in viola1:
    temp.append(i[2])
firstQ1 = stdev(temp)
print("Standard deviation of 25th percentile Viola frequency: " + str(firstQ1))

temp1 = []
for i in violin1:
    temp1.append(i[2])
firstQ2 = stdev(temp1)
print("Standard deviation of 25th percentile Violin frequency: " + str(firstQ2))

temp3 = []
for i in viola1:
    temp3.append(i[3])
thirdQ1 = stdev(temp3)
print("Standard deviation of 75th percentile Viola frequency: " + str(thirdQ1))

temp4 = []
for i in violin1:
    temp4.append(i[3])
thirdQ2 = stdev(temp4)
print("Standard deviation of 75th percentile Violin frequency: " + str(thirdQ2))

meanstdList= meanstdViolaList+meanstdViolinList
meanstd = stdev(meanstdList)
print("Standard deviation of mean frequency: " + str(meanstd))

medianstdList= medianstdViolaList+medianstdViolinList
medianstd = stdev(medianstdList)
print("Standard deviation of median frequency: " + str(medianstd))


temp0 = temp + temp1
firstQ = stdev(temp0)
print("Standard deviation of 25th percentile frequency: " + str(firstQ))

temp00 = temp3 + temp4
thirdQ = stdev(temp00)
print("Standard deviation of 75th percentile frequency: " + str(thirdQ))



Standard deviation of 25th percentile Viola frequency: 225.27338837163603
Standard deviation of 25th percentile Violin frequency: 186.12122366079353
Standard deviation of 75th percentile Viola frequency: 323.28433044966255
Standard deviation of 75th percentile Violin frequency: 400.9628709278151
Standard deviation of mean frequency: 279.705058111537
Standard deviation of median frequency: 245.5161167871702
Standard deviation of 25th percentile frequency: 206.39235211370655
Standard deviation of 75th percentile frequency: 360.5515870683298


In [12]:
os.chdir('/home/student/Downloads/new_violin_viola/classical/viola/combined_test')
x1=[]
y_test=[]
for f_name in os.listdir('/home/student/Downloads/new_violin_viola/classical/viola/combined_test'):
    if f_name.endswith('.mp3') or f_name.endswith('.wav'):
        print(f_name)
        
        x, sr = librosa.load(f_name)
        hop_length = 512
        X = librosa.stft(x)
        S = librosa.amplitude_to_db(X, ref=np.max)
        
        l1 =[]
        #by default, there are 1025 frequency bins in 0 to sr/2 (sr = 22050)

        
        hist=[]
        hist1=[]
        for i in range(len(S)):
            for j in range(len(S[0])):
        
                if S[i][j]>=(-11):
                    temp = i *((22050/2)/1025)
            
                    if temp >0:
                        hist.append(math.log2(temp))
                        hist1.append(temp)
                        
                        
        x1.append(hist)
        freqViola.append(hist1)
        y_test.append("viola")
os.chdir('/home/student/Downloads/new_violin_viola/classical/violin/combined_test')  
for f_name in os.listdir('/home/student/Downloads/new_violin_viola/classical/violin/combined_test'):
    if f_name.endswith('.mp3') or f_name.endswith('.wav'):
        print(f_name)
        
        x, sr = librosa.load(f_name)
        hop_length = 512
        X = librosa.stft(x)
        S = librosa.amplitude_to_db(X, ref=np.max)
        
        l1 =[]
        #by default, there are 1025 frequency bins in 0 to sr/2 (sr = 22050)

        
        hist=[]
        hist1=[]
        for i in range(len(S)):
            for j in range(len(S[0])):
        
                if S[i][j]>=(-11):
                    temp = i *((22050/2)/1025)
            
                    if temp >0:
                        hist.append(math.log2(temp))
                        hist1.append(temp)
                        
        x1.append(hist)
        freqViolin.append(hist1)
        y_test.append("violin")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import statistics 

X_test= [[statistics.mean(a), statistics.median(a),  min(a), max(a),np.percentile(np.array(a), 25), np.percentile(np.array(a), 75)] for a in x1]

 

Violin Sonata No 21 in E minor K 304 I Allegro_PROCESSED.wav


/home/student/.local/lib/python3.6/site-packages/librosa/core/spectrum.py:1642: UserWarning: amplitude_to_db was called on complex input so phase information will be discarded. To suppress this warning, call amplitude_to_db(np.abs(S)) instead.
  "amplitude_to_db was called on complex input so phase "


Notturno for Viola, op 42 I_PROCESSED.wav
Beethoven Sonata for viola and piano in A Major opus 69, 1st movement_PROCESSED.wav
Mozart Violin Sonata in E minor K II Tempo_PROCESSED.wav
Andante _ Allegretto in C major KV 404(Mozart)_PROCESSED.wav
Mozart Violin Sonata in E minor K I Allegro_PROCESSED.wav
Divertimento_K334Menuet_PROCESSED.wav
Mozart - Sonata for Piano and Violin in G Major, K 301 - I_PROCESSED.wav
Brahms - Lullaby for Violin and Piano duet_PROCESSED.wav
Beethoven-Sonata for Piano and Violin no 5, Spring Sonata I_PROCESSED.wav
Fantasie in C Major, D_PROCESSED.wav
Violin Sonata No 2 in A Op 12 No 2 I Allegro vivace_PROCESSED.wav


In [13]:
from numpy.random import seed
seed(14) 
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
classifier = RandomForestClassifier(max_depth=10, random_state=0)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Romantic test on Classical")
print(confusion_matrix(y_test, y_pred))
print('Accuracy' + str(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Romantic test on Classical
[[5 1]
 [2 4]]
Accuracy0.75
              precision    recall  f1-score   support

       viola       0.71      0.83      0.77         6
      violin       0.80      0.67      0.73         6

    accuracy                           0.75        12
   macro avg       0.76      0.75      0.75        12
weighted avg       0.76      0.75      0.75        12

Accuracy: 0.75


In [14]:
os.chdir('/home/student/Downloads/new_violin_viola/romantic/viola/combined_test')
x1=[]
y_test=[]
for f_name in os.listdir('/home/student/Downloads/new_violin_viola/romantic/viola/combined_test'):
    if f_name.endswith('.mp3') or f_name.endswith('.wav'):
        print(f_name)
        
        x, sr = librosa.load(f_name)
        hop_length = 512
        X = librosa.stft(x)
        S = librosa.amplitude_to_db(X, ref=np.max)
        
        l1 =[]
        #by default, there are 1025 frequency bins in 0 to sr/2 (sr = 22050)

        
        hist=[]
        hist1=[]
        for i in range(len(S)):
            for j in range(len(S[0])):
        
                if S[i][j]>=(-11):
                    temp = i *((22050/2)/1025)
            
                    if temp >0:
                        hist.append(math.log2(temp))
                        hist1.append(temp)
                        
                        
        x1.append(hist)
        freqViola.append(hist1)
        y_test.append("viola")
os.chdir('/home/student/Downloads/new_violin_viola/romantic/violin/combined_test')  
for f_name in os.listdir('/home/student/Downloads/new_violin_viola/romantic/violin/combined_test'):
    if f_name.endswith('.mp3') or f_name.endswith('.wav'):
        print(f_name)
        
        x, sr = librosa.load(f_name)
        hop_length = 512
        X = librosa.stft(x)
        S = librosa.amplitude_to_db(X, ref=np.max)
        
        l1 =[]
        #by default, there are 1025 frequency bins in 0 to sr/2 (sr = 22050)

        
        hist=[]
        hist1=[]
        for i in range(len(S)):
            for j in range(len(S[0])):
        
                if S[i][j]>=(-11):
                    temp = i *((22050/2)/1025)
            
                    if temp >0:
                        hist.append(math.log2(temp))
                        hist1.append(temp)
                        
        x1.append(hist)
        freqViolin.append(hist1)
        y_test.append("violin")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import statistics 

X_test= [[statistics.mean(a), statistics.median(a),  min(a), max(a),np.percentile(np.array(a), 25), np.percentile(np.array(a), 75)] for a in x1]

 

Adagio and Allegro in A-Flat Major Op 70 Langsam mit innigem Ausdruck (Adagio)_PROCESSED.wav


/home/student/.local/lib/python3.6/site-packages/librosa/core/spectrum.py:1642: UserWarning: amplitude_to_db was called on complex input so phase information will be discarded. To suppress this warning, call amplitude_to_db(np.abs(S)) instead.
  "amplitude_to_db was called on complex input so phase "


Märchenerzählungen for Clarinet, Viola and Piano, Op_PROCESSED.wav
Mikhail Glinka - Viola Sonata in D Minor_PROCESSED.wav
Adagio and Allegro in A-Flat Major, Op 70 Rasch und feurig_PROCESSED.wav
Tchaikovsky, Viola, Passion Confession_PROCESSED.wav
Viola Sonata in C Minor, Movement 1, Adagio - Allegro_ Felix Mendelssohn_PROCESSED.wav
5 Gedichte WWV 91 V Träume (Wagner)_PROCESSED.wav
Song Without Words Op 2 No 3 (Tchaikovsky)_PROCESSED.wav
Das Lied der Geige Op 2 (Schebek)_PROCESSED.wav
3 Pieces Op 11 Mazurka in F-Sharp Minor (Chopin)_PROCESSED.wav
Hungarian Dance No 1 WoO 1_PROCESSED.wav
Tchaikovsky, Viola, Passion Confession_PROCESSED.wav


In [15]:
from numpy.random import seed
seed(14) 
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
classifier = RandomForestClassifier(max_depth=10, random_state=0)

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Romantic test on Classical")
print(confusion_matrix(y_test, y_pred))
print('Accuracy' + str(accuracy_score(y_test, y_pred)))
print(classification_report(y_test,y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Romantic test on Classical
[[4 2]
 [4 2]]
Accuracy0.5
              precision    recall  f1-score   support

       viola       0.50      0.67      0.57         6
      violin       0.50      0.33      0.40         6

    accuracy                           0.50        12
   macro avg       0.50      0.50      0.49        12
weighted avg       0.50      0.50      0.49        12

Accuracy: 0.5


In [19]:
import plotly.express as px
import plotly.io as pio
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
components = pca.fit_transform(X_train+X_test)

fig = px.scatter(components, x=0, y=1, color=y_train+y_test)
fig.update_layout(
    title="",
    xaxis_title="First Component",
    yaxis_title="Second Component",
    font=dict(
        family="Courier New, monospace",
        size=18,
        color="#7f7f7f"
    ),
    legend=dict(
    yanchor="top",
    y=0.99,
    xanchor="left",
    x=0.00
)
)
fig.show()
#pio.write_image(fig, 'soloAll.png')
#fig.write_image("soloAll.eps")